var charData = {
    "Sirius (Midsummer Seirios)": "Azue Lane(JP)/tianlangxing_3",
    "Bismarck (Majesty of the Ironblood)": "Azue Lane(JP)/bisimai_2",
    "Ark Royal (Banquet Guardian)": "Azue Lane(JP)/huangjiafangzhou_3",
    "Taihou (Forbidden Feast)": "Azue Lane(JP)/dafeng_2",
    "Atago (Midsummer March)": "Azue Lane(JP)/aidang_2",
    "Eldridge (New Year's Handholding)": "Azue Lane(JP)/aierdeliqi_4",
    "Eldridge": "Azue Lane(JP)/aierdeliqi_5",
    "Emile Bertin (Côte d'Azur)": "Azue Lane(JP)/aimierbeierding_2",
    "Centaur (Undine of the Beach)": "Azue Lane(JP)/banrenma_2",
    "Belfast (Iridescent Rose)": "Azue Lane(JP)/beierfasite_2",
    "Javelin": "Azue Lane(JP)/biaoqiang",
    "Javelin (Beach Picnic!)": "Azue Lane(JP)/biaoqiang_3",
    "Fubuki (Music Pixy)": "Azue Lane(JP)/chuixue_3",
    "Deutschland (Service Time?!)": "Azue Lane(JP)/deyizhi_3",
    "Unicorn (Amusement Park Date)": "Azue Lane(JP)/dujiaoshou_4",
    "Dunkerque (Summer Sucré)": "Azue Lane(JP)/dunkeerke_2",
    "Honolulu (Summer Accident?!)": "Azue Lane(JP)/huonululu_3",
    "Honolulu": "Azue Lane(JP)/huonululu_5",
    "Cleveland (Gentry Knight)": "Azue Lane(JP)/kelifulan_3",
    "Laffey": "Azue Lane(JP)/lafei",
    "Laffey (New Year Rabbit)": "Azue Lane(JP)/lafei_4",
    "Ayanami": "Azue Lane(JP)/lingbo",
    "Akashi": "Azue Lane(JP)/mingshi",
    "Graf Zeppelin (Beachside Urd)": "Azue Lane(JP)/qibolin_2",
    "St. Louis (Splendor of Spring)": "Azue Lane(JP)/shengluyisi_2",
    "St. Louis (Tipsy Snow)": "Azue Lane(JP)/shengluyisi_3",
    "Tai Yuan (Clamorous Tortoise)": "Azue Lane(JP)/taiyuan_2",
    "Tirpitz (Snow-melting Summer)": "Azue Lane(JP)/tierbici_2",
    "Yukikaze": "Azue Lane(JP)/xuefeng",
    "Ibuki (Wish of a Snow Goddess)": "Azue Lane(JP)/yichui_2",
    "Z23": "Azue Lane(JP)/z23",
    "Z46 (First Summer)": "Azue Lane(JP)/z46_2",
    "Gneisenau": "Azue Lane(JP)/genaisennao_2",
    "Black Prince": "Azue Lane(JP)/heitaizi_2",
    "Ning Hai": "Azue Lane(JP)/ninghai_4",
    "Ping Hai": "Azue Lane(JP)/pinghai_4",
    "Admiral Graf Spee": "Azue Lane(JP)/sipeibojue_5",
    "Shōkaku": "Azue Lane(JP)/xianghe_2",
    "Vampire": "Azue Lane(JP)/xixuegui_4",
    "Zara": "Azue Lane(JP)/zhala_2",
};